[package]
name = "steamid-utils"
version = "0.1.2"
edition = "2024"
description = "Simple parser to detect and translate SteamID64 / Steam32 / Steam3 formats"
license = "MIT"
repository = "https://github.com/yourusername/steamid-utils"
keywords = ["steam", "steamid", "parser", "conversions", "utilities"]
categories = ["parsing", "game-development", "game-engines", "games"]

[lib]
path = "src/lib.rs"